<?xml version="1.0"?>
<package format="2">
  <name>manda_coverage</name>
  <version>0.0.0</version>
  <description>The manda_coverage package</description>

  <author>Damian Manada</author>
  
  <maintainer email="roland@ccom.unh.edu">Roland Arsenault</maintainer>

  <license>MIT</license>

  <buildtool_depend>ament_cmake_ros</buildtool_depend>
  <buildtool_depend>eigen3_cmake_module</buildtool_depend>
  <build_depend>eigen</build_depend>

  <depend>marine_nav_utilities</depend>
  <depend>nav_msgs</depend>
  <depend>nav_2d_utils</depend>
  <depend>nav2_util</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>sensor_msgs</depend>
  <depend>visualization_msgs</depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
